### ISSUE TITLE
Is the model for encoding mentions available?

### ISSUE THREAD

**Issue by zhn1010** [ariecattan/SciCo#4]
Hi. I hope you are doing well.
In section A.2 of the paper you mentioned:

> We use an encoding function f that maps the surface form of each selected c to f(c), a d dimensional vector ... the encoding function is obtained by fine-tuning a language model pre-trained on computer science papers on two semantic similarity tasks, STS and SNLI.

Is this model available?

**Comment by ariecattan** [comment]
You can easily train this model by using the [cs-roberta model](https://huggingface.co/allenai/cs_roberta_base) with the training script in sentence transformers (see https://www.sbert.net/docs/training/overview.html)
